package net.zoneland.ums.common.dal.dataobject;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

public class UmsGroup implements Serializable {

    /**  */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_GROUP.ID
     *
     * @mbggenerated
     */
    private String            id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_GROUP.GROUP_NAME
     *
     * @mbggenerated
     */
    private String            groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_GROUP.USER_ID
     *
     * @mbggenerated
     */
    private String            userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_GROUP.GMT_CREATED
     *
     * @mbggenerated
     */
    private Date              gmtCreated;

    private String            members;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_GROUP.ID
     *
     * @return the value of UMS_GROUP.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_GROUP.ID
     *
     * @param id the value for UMS_GROUP.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_GROUP.GROUP_NAME
     *
     * @return the value of UMS_GROUP.GROUP_NAME
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_GROUP.GROUP_NAME
     *
     * @param groupName the value for UMS_GROUP.GROUP_NAME
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_GROUP.USER_ID
     *
     * @return the value of UMS_GROUP.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_GROUP.USER_ID
     *
     * @param userId the value for UMS_GROUP.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_GROUP.GMT_CREATED
     *
     * @return the value of UMS_GROUP.GMT_CREATED
     *
     * @mbggenerated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_GROUP.GMT_CREATED
     *
     * @param gmtCreated the value for UMS_GROUP.GMT_CREATED
     *
     * @mbggenerated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }

    public String getMembers() {
        return members;
    }

    public void setMembers(String members) {
        this.members = members == null ? null : members;
    }

}