package net.zoneland.ums.common.dal.dataobject;

import java.util.Date;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

public class UmsGatewayRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_GATEWAY_RULE.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_GATEWAY_RULE.GATEWAY_ID
     *
     * @mbggenerated
     */
    private String gatewayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_GATEWAY_RULE.RECEIVE_REGX
     *
     * @mbggenerated
     */
    private String receiveRegx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_GATEWAY_RULE.APP_ID_REGX
     *
     * @mbggenerated
     */
    private String appIdRegx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_GATEWAY_RULE.CONTENT_REGX
     *
     * @mbggenerated
     */
    private String contentRegx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_GATEWAY_RULE.GMT_CREATED
     *
     * @mbggenerated
     */
    private Date   gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_GATEWAY_RULE.GMT_MODIFIED
     *
     * @mbggenerated
     */
    private Date   gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_GATEWAY_RULE.ID
     *
     * @return the value of UMS_GATEWAY_RULE.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_GATEWAY_RULE.ID
     *
     * @param id the value for UMS_GATEWAY_RULE.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_GATEWAY_RULE.GATEWAY_ID
     *
     * @return the value of UMS_GATEWAY_RULE.GATEWAY_ID
     *
     * @mbggenerated
     */
    public String getGatewayId() {
        return gatewayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_GATEWAY_RULE.GATEWAY_ID
     *
     * @param gatewayId the value for UMS_GATEWAY_RULE.GATEWAY_ID
     *
     * @mbggenerated
     */
    public void setGatewayId(String gatewayId) {
        this.gatewayId = gatewayId == null ? null : gatewayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_GATEWAY_RULE.RECEIVE_REGX
     *
     * @return the value of UMS_GATEWAY_RULE.RECEIVE_REGX
     *
     * @mbggenerated
     */
    public String getReceiveRegx() {
        return receiveRegx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_GATEWAY_RULE.RECEIVE_REGX
     *
     * @param receiveRegx the value for UMS_GATEWAY_RULE.RECEIVE_REGX
     *
     * @mbggenerated
     */
    public void setReceiveRegx(String receiveRegx) {
        this.receiveRegx = receiveRegx == null ? null : receiveRegx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_GATEWAY_RULE.APP_ID_REGX
     *
     * @return the value of UMS_GATEWAY_RULE.APP_ID_REGX
     *
     * @mbggenerated
     */
    public String getAppIdRegx() {
        return appIdRegx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_GATEWAY_RULE.APP_ID_REGX
     *
     * @param appIdRegx the value for UMS_GATEWAY_RULE.APP_ID_REGX
     *
     * @mbggenerated
     */
    public void setAppIdRegx(String appIdRegx) {
        this.appIdRegx = appIdRegx == null ? null : appIdRegx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_GATEWAY_RULE.CONTENT_REGX
     *
     * @return the value of UMS_GATEWAY_RULE.CONTENT_REGX
     *
     * @mbggenerated
     */
    public String getContentRegx() {
        return contentRegx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_GATEWAY_RULE.CONTENT_REGX
     *
     * @param contentRegx the value for UMS_GATEWAY_RULE.CONTENT_REGX
     *
     * @mbggenerated
     */
    public void setContentRegx(String contentRegx) {
        this.contentRegx = contentRegx == null ? null : contentRegx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_GATEWAY_RULE.GMT_CREATED
     *
     * @return the value of UMS_GATEWAY_RULE.GMT_CREATED
     *
     * @mbggenerated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_GATEWAY_RULE.GMT_CREATED
     *
     * @param gmtCreated the value for UMS_GATEWAY_RULE.GMT_CREATED
     *
     * @mbggenerated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_GATEWAY_RULE.GMT_MODIFIED
     *
     * @return the value of UMS_GATEWAY_RULE.GMT_MODIFIED
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_GATEWAY_RULE.GMT_MODIFIED
     *
     * @param gmtModified the value for UMS_GATEWAY_RULE.GMT_MODIFIED
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}