package net.zoneland.ums.common.dal.dataobject;

import java.util.Date;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

public class UmsMsgDraft {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_DRAFT.ID
     *
     * @mbggenerated
     */
    private String  id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_DRAFT.USER_ID
     *
     * @mbggenerated
     */
    private String  userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_DRAFT.RECV_ID
     *
     * @mbggenerated
     */
    private String  recvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_DRAFT.CONTENT
     *
     * @mbggenerated
     */
    private String  content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_DRAFT.ACK
     *
     * @mbggenerated
     */
    private Integer ack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_DRAFT.SEND_TIME
     *
     * @mbggenerated
     */
    private Date    sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_DRAFT.VALID_TIME
     *
     * @mbggenerated
     */
    private String    validTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_DRAFT.GMT_CREATED
     *
     * @mbggenerated
     */
    private Date    gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_DRAFT.GMT_MODIFIED
     *
     * @mbggenerated
     */
    private Date    gmtModified;
    
    /**
     * 身份  0：个人  1：组织
     */
    private String  identity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_DRAFT.ID
     *
     * @return the value of UMS_MSG_DRAFT.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_DRAFT.ID
     *
     * @param id the value for UMS_MSG_DRAFT.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_DRAFT.USER_ID
     *
     * @return the value of UMS_MSG_DRAFT.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_DRAFT.USER_ID
     *
     * @param userId the value for UMS_MSG_DRAFT.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_DRAFT.RECV_ID
     *
     * @return the value of UMS_MSG_DRAFT.RECV_ID
     *
     * @mbggenerated
     */
    public String getRecvId() {
        return recvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_DRAFT.RECV_ID
     *
     * @param recvId the value for UMS_MSG_DRAFT.RECV_ID
     *
     * @mbggenerated
     */
    public void setRecvId(String recvId) {
        this.recvId = recvId == null ? null : recvId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_DRAFT.CONTENT
     *
     * @return the value of UMS_MSG_DRAFT.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_DRAFT.CONTENT
     *
     * @param content the value for UMS_MSG_DRAFT.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_DRAFT.ACK
     *
     * @return the value of UMS_MSG_DRAFT.ACK
     *
     * @mbggenerated
     */
    public Integer getAck() {
        return ack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_DRAFT.ACK
     *
     * @param ack the value for UMS_MSG_DRAFT.ACK
     *
     * @mbggenerated
     */
    public void setAck(Integer ack) {
        this.ack = ack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_DRAFT.SEND_TIME
     *
     * @return the value of UMS_MSG_DRAFT.SEND_TIME
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_DRAFT.SEND_TIME
     *
     * @param sendTime the value for UMS_MSG_DRAFT.SEND_TIME
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_DRAFT.VALID_TIME
     *
     * @return the value of UMS_MSG_DRAFT.VALID_TIME
     *
     * @mbggenerated
     */
    public String getValidTime() {
        return validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_DRAFT.VALID_TIME
     *
     * @param validTime the value for UMS_MSG_DRAFT.VALID_TIME
     *
     * @mbggenerated
     */
    public void setValidTime(String validTime) {
        this.validTime = validTime == null ? null : validTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_DRAFT.GMT_CREATED
     *
     * @return the value of UMS_MSG_DRAFT.GMT_CREATED
     *
     * @mbggenerated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_DRAFT.GMT_CREATED
     *
     * @param gmtCreated the value for UMS_MSG_DRAFT.GMT_CREATED
     *
     * @mbggenerated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_DRAFT.GMT_MODIFIED
     *
     * @return the value of UMS_MSG_DRAFT.GMT_MODIFIED
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_DRAFT.GMT_MODIFIED
     *
     * @param gmtModified the value for UMS_MSG_DRAFT.GMT_MODIFIED
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }

    public String getIdentity() {
        return identity;
    }

    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }
    
    
}