package net.zoneland.ums.common.dal.dataobject;

import java.util.Date;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

public class UmsOutReply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_OUT_REPLY.ID
     *
     * @mbggenerated
     */
    private String  id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_OUT_REPLY.REPLY
     *
     * @mbggenerated
     */
    private String  reply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_OUT_REPLY.REPLY_DES
     *
     * @mbggenerated
     */
    private Integer replyDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_OUT_REPLY.SEND_ID
     *
     * @mbggenerated
     */
    private String  sendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_OUT_REPLY.RECEIVE_ID
     *
     * @mbggenerated
     */
    private String  receiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_OUT_REPLY.BATCH_NO
     *
     * @mbggenerated
     */
    private String  batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_OUT_REPLY.SERIAL_NO
     *
     * @mbggenerated
     */
    private String  serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_OUT_REPLY.APP_ID
     *
     * @mbggenerated
     */
    private String  appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_OUT_REPLY.SUB_APP
     *
     * @mbggenerated
     */
    private String  subApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_OUT_REPLY.APP_SERIAL_NO
     *
     * @mbggenerated
     */
    private String  appSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_OUT_REPLY.ACK
     *
     * @mbggenerated
     */
    private Integer ack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_OUT_REPLY.GMT_CREATED
     *
     * @mbggenerated
     */
    private Date    gmtCreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_OUT_REPLY.ID
     *
     * @return the value of UMS_OUT_REPLY.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_OUT_REPLY.ID
     *
     * @param id the value for UMS_OUT_REPLY.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_OUT_REPLY.REPLY
     *
     * @return the value of UMS_OUT_REPLY.REPLY
     *
     * @mbggenerated
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_OUT_REPLY.REPLY
     *
     * @param reply the value for UMS_OUT_REPLY.REPLY
     *
     * @mbggenerated
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_OUT_REPLY.REPLY_DES
     *
     * @return the value of UMS_OUT_REPLY.REPLY_DES
     *
     * @mbggenerated
     */
    public Integer getReplyDes() {
        return replyDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_OUT_REPLY.REPLY_DES
     *
     * @param replyDes the value for UMS_OUT_REPLY.REPLY_DES
     *
     * @mbggenerated
     */
    public void setReplyDes(Integer replyDes) {
        this.replyDes = replyDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_OUT_REPLY.SEND_ID
     *
     * @return the value of UMS_OUT_REPLY.SEND_ID
     *
     * @mbggenerated
     */
    public String getSendId() {
        return sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_OUT_REPLY.SEND_ID
     *
     * @param sendId the value for UMS_OUT_REPLY.SEND_ID
     *
     * @mbggenerated
     */
    public void setSendId(String sendId) {
        this.sendId = sendId == null ? null : sendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_OUT_REPLY.RECEIVE_ID
     *
     * @return the value of UMS_OUT_REPLY.RECEIVE_ID
     *
     * @mbggenerated
     */
    public String getReceiveId() {
        return receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_OUT_REPLY.RECEIVE_ID
     *
     * @param receiveId the value for UMS_OUT_REPLY.RECEIVE_ID
     *
     * @mbggenerated
     */
    public void setReceiveId(String receiveId) {
        this.receiveId = receiveId == null ? null : receiveId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_OUT_REPLY.BATCH_NO
     *
     * @return the value of UMS_OUT_REPLY.BATCH_NO
     *
     * @mbggenerated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_OUT_REPLY.BATCH_NO
     *
     * @param batchNo the value for UMS_OUT_REPLY.BATCH_NO
     *
     * @mbggenerated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_OUT_REPLY.SERIAL_NO
     *
     * @return the value of UMS_OUT_REPLY.SERIAL_NO
     *
     * @mbggenerated
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_OUT_REPLY.SERIAL_NO
     *
     * @param serialNo the value for UMS_OUT_REPLY.SERIAL_NO
     *
     * @mbggenerated
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_OUT_REPLY.APP_ID
     *
     * @return the value of UMS_OUT_REPLY.APP_ID
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_OUT_REPLY.APP_ID
     *
     * @param appId the value for UMS_OUT_REPLY.APP_ID
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_OUT_REPLY.SUB_APP
     *
     * @return the value of UMS_OUT_REPLY.SUB_APP
     *
     * @mbggenerated
     */
    public String getSubApp() {
        return subApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_OUT_REPLY.SUB_APP
     *
     * @param subApp the value for UMS_OUT_REPLY.SUB_APP
     *
     * @mbggenerated
     */
    public void setSubApp(String subApp) {
        this.subApp = subApp == null ? null : subApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_OUT_REPLY.APP_SERIAL_NO
     *
     * @return the value of UMS_OUT_REPLY.APP_SERIAL_NO
     *
     * @mbggenerated
     */
    public String getAppSerialNo() {
        return appSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_OUT_REPLY.APP_SERIAL_NO
     *
     * @param appSerialNo the value for UMS_OUT_REPLY.APP_SERIAL_NO
     *
     * @mbggenerated
     */
    public void setAppSerialNo(String appSerialNo) {
        this.appSerialNo = appSerialNo == null ? null : appSerialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_OUT_REPLY.ACK
     *
     * @return the value of UMS_OUT_REPLY.ACK
     *
     * @mbggenerated
     */
    public Integer getAck() {
        return ack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_OUT_REPLY.ACK
     *
     * @param ack the value for UMS_OUT_REPLY.ACK
     *
     * @mbggenerated
     */
    public void setAck(Integer ack) {
        this.ack = ack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_OUT_REPLY.GMT_CREATED
     *
     * @return the value of UMS_OUT_REPLY.GMT_CREATED
     *
     * @mbggenerated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_OUT_REPLY.GMT_CREATED
     *
     * @param gmtCreated the value for UMS_OUT_REPLY.GMT_CREATED
     *
     * @mbggenerated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}