package net.zoneland.ums.common.dal.dataobject;

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

public class UmsOrganization implements Serializable {

    /**  */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ORGANIZATION.ID
     *
     * @mbggenerated
     */
    private String            id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ORGANIZATION.ORG_NAME
     *
     * @mbggenerated
     */
    private String            orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ORGANIZATION.PARENT_ID
     *
     * @mbggenerated
     */
    private String            parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ORGANIZATION.ORDER
     *
     * @mbggenerated
     */
    private Integer           order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ORGANIZATION.ORG_MANAGER
     *
     * @mbggenerated
     */
    private String            orgManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ORGANIZATION.ORG_VICE_MANAGER
     *
     * @mbggenerated
     */
    private String            orgViceManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_ORGANIZATION.GMT_CREATED
     *
     * @mbggenerated
     */
    private Date              gmtCreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ORGANIZATION.ID
     *
     * @return the value of UMS_ORGANIZATION.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ORGANIZATION.ID
     *
     * @param id the value for UMS_ORGANIZATION.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ORGANIZATION.ORG_NAME
     *
     * @return the value of UMS_ORGANIZATION.ORG_NAME
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ORGANIZATION.ORG_NAME
     *
     * @param orgName the value for UMS_ORGANIZATION.ORG_NAME
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ORGANIZATION.PARENT_ID
     *
     * @return the value of UMS_ORGANIZATION.PARENT_ID
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ORGANIZATION.PARENT_ID
     *
     * @param parentId the value for UMS_ORGANIZATION.PARENT_ID
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ORGANIZATION.ORDER
     *
     * @return the value of UMS_ORGANIZATION.ORDER
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ORGANIZATION.ORDER
     *
     * @param order the value for UMS_ORGANIZATION.ORDER
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ORGANIZATION.ORG_MANAGER
     *
     * @return the value of UMS_ORGANIZATION.ORG_MANAGER
     *
     * @mbggenerated
     */
    public String getOrgManager() {
        return orgManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ORGANIZATION.ORG_MANAGER
     *
     * @param orgManager the value for UMS_ORGANIZATION.ORG_MANAGER
     *
     * @mbggenerated
     */
    public void setOrgManager(String orgManager) {
        this.orgManager = orgManager == null ? null : orgManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ORGANIZATION.ORG_VICE_MANAGER
     *
     * @return the value of UMS_ORGANIZATION.ORG_VICE_MANAGER
     *
     * @mbggenerated
     */
    public String getOrgViceManager() {
        return orgViceManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ORGANIZATION.ORG_VICE_MANAGER
     *
     * @param orgViceManager the value for UMS_ORGANIZATION.ORG_VICE_MANAGER
     *
     * @mbggenerated
     */
    public void setOrgViceManager(String orgViceManager) {
        this.orgViceManager = orgViceManager == null ? null : orgViceManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_ORGANIZATION.GMT_CREATED
     *
     * @return the value of UMS_ORGANIZATION.GMT_CREATED
     *
     * @mbggenerated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_ORGANIZATION.GMT_CREATED
     *
     * @param gmtCreated the value for UMS_ORGANIZATION.GMT_CREATED
     *
     * @mbggenerated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}