package net.zoneland.ums.common.dal.dataobject;

import java.util.Date;

public class UmsTelDescribe {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_TEL_DESCRIBE.TEL
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_TEL_DESCRIBE.PROVINCE
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_TEL_DESCRIBE.SIMTYPE
     *
     * @mbggenerated
     */
    private String simtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_TEL_DESCRIBE.CITY
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_TEL_DESCRIBE.GMT_CREATED
     *
     * @mbggenerated
     */
    private Date gmtCreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_TEL_DESCRIBE.TEL
     *
     * @return the value of UMS_TEL_DESCRIBE.TEL
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_TEL_DESCRIBE.TEL
     *
     * @param tel the value for UMS_TEL_DESCRIBE.TEL
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_TEL_DESCRIBE.PROVINCE
     *
     * @return the value of UMS_TEL_DESCRIBE.PROVINCE
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_TEL_DESCRIBE.PROVINCE
     *
     * @param province the value for UMS_TEL_DESCRIBE.PROVINCE
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_TEL_DESCRIBE.SIMTYPE
     *
     * @return the value of UMS_TEL_DESCRIBE.SIMTYPE
     *
     * @mbggenerated
     */
    public String getSimtype() {
        return simtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_TEL_DESCRIBE.SIMTYPE
     *
     * @param simtype the value for UMS_TEL_DESCRIBE.SIMTYPE
     *
     * @mbggenerated
     */
    public void setSimtype(String simtype) {
        this.simtype = simtype == null ? null : simtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_TEL_DESCRIBE.CITY
     *
     * @return the value of UMS_TEL_DESCRIBE.CITY
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_TEL_DESCRIBE.CITY
     *
     * @param city the value for UMS_TEL_DESCRIBE.CITY
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_TEL_DESCRIBE.GMT_CREATED
     *
     * @return the value of UMS_TEL_DESCRIBE.GMT_CREATED
     *
     * @mbggenerated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_TEL_DESCRIBE.GMT_CREATED
     *
     * @param gmtCreated the value for UMS_TEL_DESCRIBE.GMT_CREATED
     *
     * @mbggenerated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }
}