package net.zoneland.ums.common.dal.dataobject;

import java.util.Date;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

public class UmsUserRoleAppRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_USER_ROLE_APP_REL.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_USER_ROLE_APP_REL.ROLE_USER_REL_ID
     *
     * @mbggenerated
     */
    private String roleUserRelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_USER_ROLE_APP_REL.APP_ID
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_USER_ROLE_APP_REL.GMT_CREATED
     *
     * @mbggenerated
     */
    private Date   gmtCreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_USER_ROLE_APP_REL.ID
     *
     * @return the value of UMS_USER_ROLE_APP_REL.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_USER_ROLE_APP_REL.ID
     *
     * @param id the value for UMS_USER_ROLE_APP_REL.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_USER_ROLE_APP_REL.ROLE_USER_REL_ID
     *
     * @return the value of UMS_USER_ROLE_APP_REL.ROLE_USER_REL_ID
     *
     * @mbggenerated
     */
    public String getRoleUserRelId() {
        return roleUserRelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_USER_ROLE_APP_REL.ROLE_USER_REL_ID
     *
     * @param roleUserRelId the value for UMS_USER_ROLE_APP_REL.ROLE_USER_REL_ID
     *
     * @mbggenerated
     */
    public void setRoleUserRelId(String roleUserRelId) {
        this.roleUserRelId = roleUserRelId == null ? null : roleUserRelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_USER_ROLE_APP_REL.APP_ID
     *
     * @return the value of UMS_USER_ROLE_APP_REL.APP_ID
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_USER_ROLE_APP_REL.APP_ID
     *
     * @param appId the value for UMS_USER_ROLE_APP_REL.APP_ID
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_USER_ROLE_APP_REL.GMT_CREATED
     *
     * @return the value of UMS_USER_ROLE_APP_REL.GMT_CREATED
     *
     * @mbggenerated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_USER_ROLE_APP_REL.GMT_CREATED
     *
     * @param gmtCreated the value for UMS_USER_ROLE_APP_REL.GMT_CREATED
     *
     * @mbggenerated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}