CREATE TEMPORARY TABLESPACE monitor_temp TEMPFILE 'e:\app\data\monitor_temp01.dbf' SIZE 32M AUTOEXTEND ON NEXT 32M MAXSIZE 2048M EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE monitor_data LOGGING DATAFILE 'e:\app\data\MONITOR_DATA01.DBF' SIZE 32M  AUTOEXTEND ON NEXT 32M MAXSIZE 2048M EXTENT MANAGEMENT LOCAL;

CREATE USER monitor IDENTIFIED BY monitor DEFAULT TABLESPACE MONITOR_DATA TEMPORARY TABLESPACE monitor_temp;

alter user monitor quota unlimited on MONITOR_DATA;


GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY VIEW ,CREATE ANY INDEX, CREATE ANY PROCEDURE,ALTER ANY TABLE, ALTER ANY PROCEDURE,DROP ANY TABLE,DROP ANY VIEW,DROP ANY INDEX,DROP ANY PROCEDURE,SELECT ANY TABLE,INSERT ANY TABLE,UPDATE ANY TABLE,DELETE ANY TABLE TO monitor;