package net.zoneland.ums.common.dal.bo;

import java.io.Serializable;
import java.util.Date;

import net.zoneland.ums.common.dal.dataobject.UmsAppInfo;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

public class UmsMsgOutDO implements Serializable {
    /**  */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.ID
     *
     * @mbggenerated
     */
    private String            id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.BATCH_NO
     *
     * @mbggenerated
     */
    private String            batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.SERIAL_NO
     *
     * @mbggenerated
     */
    private Integer           serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.SEND_ID
     *
     * @mbggenerated
     */
    private String            sendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.USER_ID
     *
     * @mbggenerated
     */
    private String            userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.RECV_ID
     *
     * @mbggenerated
     */
    private String            recvId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.CONTENT
     *
     * @mbggenerated
     */
    private String            content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.MSG_TYPE
     *
     * @mbggenerated
     */
    private Integer           msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.STATUS
     *
     * @mbggenerated
     */
    private String            status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.APP_ID
     *
     * @mbggenerated
     */
    private String            appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.SUB_APP
     *
     * @mbggenerated
     */
    private String            subApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.APP_SERIAL_NO
     *
     * @mbggenerated
     */
    private String            appSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.MEDIA_ID
     *
     * @mbggenerated
     */
    private String            mediaId;

    private String            gatewayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.RET_CODE
     *
     * @mbggenerated
     */
    private String            retCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.ERROR_MSG
     *
     * @mbggenerated
     */
    private String            errorMsg;

    private String            templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.ACK
     *
     * @mbggenerated
     */
    private Integer           ack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.REPLY
     *
     * @mbggenerated
     */
    private String            reply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.RETRY
     *
     * @mbggenerated
     */
    private Integer           retry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.PRIORITY
     *
     * @mbggenerated
     */
    private Integer           priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.BATCH_MODE
     *
     * @mbggenerated
     */
    private String            batchMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.CONTENT_MODE
     *
     * @mbggenerated
     */
    private Integer           contentMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.TIME_SET_FLAG
     *
     * @mbggenerated
     */
    private String            timeSetFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.SET_TIME
     *
     * @mbggenerated
     */
    private Date              setTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.REPLY_DES
     *
     * @mbggenerated
     */
    private String            replyDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.FEE
     *
     * @mbggenerated
     */
    private Integer           fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.FEE_TYPE
     *
     * @mbggenerated
     */
    private Integer           feeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.MSG_ID
     *
     * @mbggenerated
     */
    private String            msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.DOCOUNT
     *
     * @mbggenerated
     */
    private Integer           docount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.SEND_TIME
     *
     * @mbggenerated
     */
    private Date              sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.VALID_TIME
     *
     * @mbggenerated
     */
    private Date              validTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.GROUP_SERIAL
     *
     * @mbggenerated
     */
    private String            groupSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.ORG_NO
     *
     * @mbggenerated
     */
    private String            orgNo;

    private String            areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.FLOW_NO
     *
     * @mbggenerated
     */
    private String            flowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.CREATE_USER
     *
     * @mbggenerated
     */
    private String            createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.BIZ_TYPE
     *
     * @mbggenerated
     */
    private String            bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.BIZ_NAME
     *
     * @mbggenerated
     */
    private String            bizName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.GMT_CREATED
     *
     * @mbggenerated
     */
    private Date              gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMS_MSG_OUT.GMT_MODIFIED
     *
     * @mbggenerated
     */
    private Date              gmtModified;

    private UmsAppInfo        app;
    /**
     * 身份  0：个人  1：组织
     */
    private String            identity;

    private String            recvName;              // 接收方姓名

    private String            userName;              // 发送方姓名

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.ID
     *
     * @return the value of UMS_MSG_OUT.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.ID
     *
     * @param id the value for UMS_MSG_OUT.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.BATCH_NO
     *
     * @return the value of UMS_MSG_OUT.BATCH_NO
     *
     * @mbggenerated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.BATCH_NO
     *
     * @param batchNo the value for UMS_MSG_OUT.BATCH_NO
     *
     * @mbggenerated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.SERIAL_NO
     *
     * @return the value of UMS_MSG_OUT.SERIAL_NO
     *
     * @mbggenerated
     */
    public Integer getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.SERIAL_NO
     *
     * @param serialNo the value for UMS_MSG_OUT.SERIAL_NO
     *
     * @mbggenerated
     */
    public void setSerialNo(Integer serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.SEND_ID
     *
     * @return the value of UMS_MSG_OUT.SEND_ID
     *
     * @mbggenerated
     */
    public String getSendId() {
        return sendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.SEND_ID
     *
     * @param sendId the value for UMS_MSG_OUT.SEND_ID
     *
     * @mbggenerated
     */
    public void setSendId(String sendId) {
        this.sendId = sendId == null ? null : sendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.USER_ID
     *
     * @return the value of UMS_MSG_OUT.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.USER_ID
     *
     * @param userId the value for UMS_MSG_OUT.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.RECV_ID
     *
     * @return the value of UMS_MSG_OUT.RECV_ID
     *
     * @mbggenerated
     */
    public String getRecvId() {
        return recvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.RECV_ID
     *
     * @param recvId the value for UMS_MSG_OUT.RECV_ID
     *
     * @mbggenerated
     */
    public void setRecvId(String recvId) {
        this.recvId = recvId == null ? null : recvId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.CONTENT
     *
     * @return the value of UMS_MSG_OUT.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.CONTENT
     *
     * @param content the value for UMS_MSG_OUT.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.MSG_TYPE
     *
     * @return the value of UMS_MSG_OUT.MSG_TYPE
     *
     * @mbggenerated
     */
    public Integer getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.MSG_TYPE
     *
     * @param msgType the value for UMS_MSG_OUT.MSG_TYPE
     *
     * @mbggenerated
     */
    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.STATUS
     *
     * @return the value of UMS_MSG_OUT.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.STATUS
     *
     * @param status the value for UMS_MSG_OUT.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.APP_ID
     *
     * @return the value of UMS_MSG_OUT.APP_ID
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.APP_ID
     *
     * @param appId the value for UMS_MSG_OUT.APP_ID
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.SUB_APP
     *
     * @return the value of UMS_MSG_OUT.SUB_APP
     *
     * @mbggenerated
     */
    public String getSubApp() {
        return subApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.SUB_APP
     *
     * @param subApp the value for UMS_MSG_OUT.SUB_APP
     *
     * @mbggenerated
     */
    public void setSubApp(String subApp) {
        this.subApp = subApp == null ? null : subApp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.APP_SERIAL_NO
     *
     * @return the value of UMS_MSG_OUT.APP_SERIAL_NO
     *
     * @mbggenerated
     */
    public String getAppSerialNo() {
        return appSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.APP_SERIAL_NO
     *
     * @param appSerialNo the value for UMS_MSG_OUT.APP_SERIAL_NO
     *
     * @mbggenerated
     */
    public void setAppSerialNo(String appSerialNo) {
        this.appSerialNo = appSerialNo == null ? null : appSerialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.MEDIA_ID
     *
     * @return the value of UMS_MSG_OUT.MEDIA_ID
     *
     * @mbggenerated
     */
    public String getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.MEDIA_ID
     *
     * @param mediaId the value for UMS_MSG_OUT.MEDIA_ID
     *
     * @mbggenerated
     */
    public void setMediaId(String mediaId) {
        this.mediaId = mediaId == null ? null : mediaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.RET_CODE
     *
     * @return the value of UMS_MSG_OUT.RET_CODE
     *
     * @mbggenerated
     */
    public String getRetCode() {
        return retCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.RET_CODE
     *
     * @param retCode the value for UMS_MSG_OUT.RET_CODE
     *
     * @mbggenerated
     */
    public void setRetCode(String retCode) {
        this.retCode = retCode == null ? null : retCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.ERROR_MSG
     *
     * @return the value of UMS_MSG_OUT.ERROR_MSG
     *
     * @mbggenerated
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.ERROR_MSG
     *
     * @param errorMsg the value for UMS_MSG_OUT.ERROR_MSG
     *
     * @mbggenerated
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg == null ? null : errorMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.ACK
     *
     * @return the value of UMS_MSG_OUT.ACK
     *
     * @mbggenerated
     */
    public Integer getAck() {
        return ack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.ACK
     *
     * @param ack the value for UMS_MSG_OUT.ACK
     *
     * @mbggenerated
     */
    public void setAck(Integer ack) {
        this.ack = ack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.REPLY
     *
     * @return the value of UMS_MSG_OUT.REPLY
     *
     * @mbggenerated
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.REPLY
     *
     * @param reply the value for UMS_MSG_OUT.REPLY
     *
     * @mbggenerated
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.RETRY
     *
     * @return the value of UMS_MSG_OUT.RETRY
     *
     * @mbggenerated
     */
    public Integer getRetry() {
        return retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.RETRY
     *
     * @param retry the value for UMS_MSG_OUT.RETRY
     *
     * @mbggenerated
     */
    public void setRetry(Integer retry) {
        this.retry = retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.PRIORITY
     *
     * @return the value of UMS_MSG_OUT.PRIORITY
     *
     * @mbggenerated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.PRIORITY
     *
     * @param priority the value for UMS_MSG_OUT.PRIORITY
     *
     * @mbggenerated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.BATCH_MODE
     *
     * @return the value of UMS_MSG_OUT.BATCH_MODE
     *
     * @mbggenerated
     */
    public String getBatchMode() {
        return batchMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.BATCH_MODE
     *
     * @param batchMode the value for UMS_MSG_OUT.BATCH_MODE
     *
     * @mbggenerated
     */
    public void setBatchMode(String batchMode) {
        this.batchMode = batchMode == null ? null : batchMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.CONTENT_MODE
     *
     * @return the value of UMS_MSG_OUT.CONTENT_MODE
     *
     * @mbggenerated
     */
    public Integer getContentMode() {
        return contentMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.CONTENT_MODE
     *
     * @param contentMode the value for UMS_MSG_OUT.CONTENT_MODE
     *
     * @mbggenerated
     */
    public void setContentMode(Integer contentMode) {
        this.contentMode = contentMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.TIME_SET_FLAG
     *
     * @return the value of UMS_MSG_OUT.TIME_SET_FLAG
     *
     * @mbggenerated
     */
    public String getTimeSetFlag() {
        return timeSetFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.TIME_SET_FLAG
     *
     * @param timeSetFlag the value for UMS_MSG_OUT.TIME_SET_FLAG
     *
     * @mbggenerated
     */
    public void setTimeSetFlag(String timeSetFlag) {
        this.timeSetFlag = timeSetFlag == null ? null : timeSetFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.SET_TIME
     *
     * @return the value of UMS_MSG_OUT.SET_TIME
     *
     * @mbggenerated
     */
    public Date getSetTime() {
        return setTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.SET_TIME
     *
     * @param setTime the value for UMS_MSG_OUT.SET_TIME
     *
     * @mbggenerated
     */
    public void setSetTime(Date setTime) {
        this.setTime = setTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.REPLY_DES
     *
     * @return the value of UMS_MSG_OUT.REPLY_DES
     *
     * @mbggenerated
     */
    public String getReplyDes() {
        return replyDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.REPLY_DES
     *
     * @param replyDes the value for UMS_MSG_OUT.REPLY_DES
     *
     * @mbggenerated
     */
    public void setReplyDes(String replyDes) {
        this.replyDes = replyDes == null ? null : replyDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.FEE
     *
     * @return the value of UMS_MSG_OUT.FEE
     *
     * @mbggenerated
     */
    public Integer getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.FEE
     *
     * @param fee the value for UMS_MSG_OUT.FEE
     *
     * @mbggenerated
     */
    public void setFee(Integer fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.FEE_TYPE
     *
     * @return the value of UMS_MSG_OUT.FEE_TYPE
     *
     * @mbggenerated
     */
    public Integer getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.FEE_TYPE
     *
     * @param feeType the value for UMS_MSG_OUT.FEE_TYPE
     *
     * @mbggenerated
     */
    public void setFeeType(Integer feeType) {
        this.feeType = feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.MSG_ID
     *
     * @return the value of UMS_MSG_OUT.MSG_ID
     *
     * @mbggenerated
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.MSG_ID
     *
     * @param msgId the value for UMS_MSG_OUT.MSG_ID
     *
     * @mbggenerated
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId == null ? null : msgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.DOCOUNT
     *
     * @return the value of UMS_MSG_OUT.DOCOUNT
     *
     * @mbggenerated
     */
    public Integer getDocount() {
        return docount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.DOCOUNT
     *
     * @param docount the value for UMS_MSG_OUT.DOCOUNT
     *
     * @mbggenerated
     */
    public void setDocount(Integer docount) {
        this.docount = docount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.SEND_TIME
     *
     * @return the value of UMS_MSG_OUT.SEND_TIME
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.SEND_TIME
     *
     * @param sendTime the value for UMS_MSG_OUT.SEND_TIME
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.VALID_TIME
     *
     * @return the value of UMS_MSG_OUT.VALID_TIME
     *
     * @mbggenerated
     */
    public Date getValidTime() {
        return validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.VALID_TIME
     *
     * @param validTime the value for UMS_MSG_OUT.VALID_TIME
     *
     * @mbggenerated
     */
    public void setValidTime(Date validTime) {
        this.validTime = validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.GROUP_SERIAL
     *
     * @return the value of UMS_MSG_OUT.GROUP_SERIAL
     *
     * @mbggenerated
     */
    public String getGroupSerial() {
        return groupSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.GROUP_SERIAL
     *
     * @param groupSerial the value for UMS_MSG_OUT.GROUP_SERIAL
     *
     * @mbggenerated
     */
    public void setGroupSerial(String groupSerial) {
        this.groupSerial = groupSerial == null ? null : groupSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.ORG_NO
     *
     * @return the value of UMS_MSG_OUT.ORG_NO
     *
     * @mbggenerated
     */
    public String getOrgNo() {
        return orgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.ORG_NO
     *
     * @param orgNo the value for UMS_MSG_OUT.ORG_NO
     *
     * @mbggenerated
     */
    public void setOrgNo(String orgNo) {
        this.orgNo = orgNo == null ? null : orgNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.FLOW_NO
     *
     * @return the value of UMS_MSG_OUT.FLOW_NO
     *
     * @mbggenerated
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.FLOW_NO
     *
     * @param flowNo the value for UMS_MSG_OUT.FLOW_NO
     *
     * @mbggenerated
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo == null ? null : flowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.CREATE_USER
     *
     * @return the value of UMS_MSG_OUT.CREATE_USER
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.CREATE_USER
     *
     * @param createUser the value for UMS_MSG_OUT.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.BIZ_TYPE
     *
     * @return the value of UMS_MSG_OUT.BIZ_TYPE
     *
     * @mbggenerated
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.BIZ_TYPE
     *
     * @param bizType the value for UMS_MSG_OUT.BIZ_TYPE
     *
     * @mbggenerated
     */
    public void setBizType(String bizType) {
        this.bizType = bizType == null ? null : bizType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.BIZ_NAME
     *
     * @return the value of UMS_MSG_OUT.BIZ_NAME
     *
     * @mbggenerated
     */
    public String getBizName() {
        return bizName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.BIZ_NAME
     *
     * @param bizName the value for UMS_MSG_OUT.BIZ_NAME
     *
     * @mbggenerated
     */
    public void setBizName(String bizName) {
        this.bizName = bizName == null ? null : bizName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.GMT_CREATED
     *
     * @return the value of UMS_MSG_OUT.GMT_CREATED
     *
     * @mbggenerated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.GMT_CREATED
     *
     * @param gmtCreated the value for UMS_MSG_OUT.GMT_CREATED
     *
     * @mbggenerated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMS_MSG_OUT.GMT_MODIFIED
     *
     * @return the value of UMS_MSG_OUT.GMT_MODIFIED
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMS_MSG_OUT.GMT_MODIFIED
     *
     * @param gmtModified the value for UMS_MSG_OUT.GMT_MODIFIED
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }

    public UmsAppInfo getApp() {
        return app;
    }

    public void setApp(UmsAppInfo app) {
        this.app = app;
    }

    public String getIdentity() {
        return identity;
    }

    public void setIdentity(String identity) {
        this.identity = identity;
    }

    /**
     * Getter method for property <tt>gatewayName</tt>.
     * 
     * @return property value of gatewayName
     */
    public String getGatewayName() {
        return gatewayName;
    }

    /**
     * Setter method for property <tt>gatewayName</tt>.
     * 
     * @param gatewayName value to be assigned to property gatewayName
     */
    public void setGatewayName(String gatewayName) {
        this.gatewayName = gatewayName;
    }

    /**
     * Getter method for property <tt>areaName</tt>.
     * 
     * @return property value of areaName
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * Setter method for property <tt>areaName</tt>.
     * 
     * @param areaName value to be assigned to property areaName
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * Getter method for property <tt>templateId</tt>.
     * 
     * @return property value of templateId
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * Setter method for property <tt>templateId</tt>.
     * 
     * @param templateId value to be assigned to property templateId
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId;
    }

    /**
     * Getter method for property <tt>recvName</tt>.
     * 
     * @return property value of recvName
     */
    public String getRecvName() {
        return recvName;
    }

    /**
     * Setter method for property <tt>recvName</tt>.
     * 
     * @param recvName value to be assigned to property recvName
     */
    public void setRecvName(String recvName) {
        this.recvName = recvName;
    }

    /**
     * Getter method for property <tt>userName</tt>.
     * 
     * @return property value of userName
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Setter method for property <tt>userName</tt>.
     * 
     * @param userName value to be assigned to property userName
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

}